// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc0QPrYobv7or7FXyA9MNP_Uwq5pSSVuw',
    appId: '1:38223529044:web:c383ea15ff8073a3fed9c1',
    messagingSenderId: '38223529044',
    projectId: 'login-verificati-1712467959577',
    authDomain: 'login-verificati-1712467959577.firebaseapp.com',
    storageBucket: 'login-verificati-1712467959577.firebasestorage.app',
    measurementId: 'G-9MPTZ6GMBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAehtoujyxr3CxUDgAcdNMKG7nbOs-5J4U',
    appId: '1:38223529044:android:6078ce7e79716ebefed9c1',
    messagingSenderId: '38223529044',
    projectId: 'login-verificati-1712467959577',
    storageBucket: 'login-verificati-1712467959577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxF_sI4vGYKb5ImP_5uYUjhHakE98ZxEc',
    appId: '1:38223529044:ios:d44a9cd59d8a1b75fed9c1',
    messagingSenderId: '38223529044',
    projectId: 'login-verificati-1712467959577',
    storageBucket: 'login-verificati-1712467959577.firebasestorage.app',
    iosBundleId: 'com.example.scvWaterEmu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxF_sI4vGYKb5ImP_5uYUjhHakE98ZxEc',
    appId: '1:38223529044:ios:d44a9cd59d8a1b75fed9c1',
    messagingSenderId: '38223529044',
    projectId: 'login-verificati-1712467959577',
    storageBucket: 'login-verificati-1712467959577.firebasestorage.app',
    iosBundleId: 'com.example.scvWaterEmu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc0QPrYobv7or7FXyA9MNP_Uwq5pSSVuw',
    appId: '1:38223529044:web:dd655f5600fcf283fed9c1',
    messagingSenderId: '38223529044',
    projectId: 'login-verificati-1712467959577',
    authDomain: 'login-verificati-1712467959577.firebaseapp.com',
    storageBucket: 'login-verificati-1712467959577.firebasestorage.app',
    measurementId: 'G-BQ86TT669P',
  );

}